network:
  listenAddr: "/ip4/0.0.0.0/tcp/53799"
  bootstrapPeers:
    - "/ip4/127.0.0.1/tcp/53798/p2p/QmV5SMTt4wRYtau44z54fFWCuZ1Rm8wCx486QJRG3vobwU"
  protocolTimeout: "30s"

storage:
  dataDir: "./data"
  maxCapacityGB: 20
  reservedSpaceGB: 10

api:
  listenAddr: ":5556"