network:
  listenAddr: "/ip4/0.0.0.0/tcp/53798"
  privateKey: "CAMSeTB3AgEBBCBTUISUaHBmdWJoih/VYXyt60jzjYBWhYWzjn+Ed60+LKAKBggqhkjOPQMBB6FEA0IABP1HQJFyVtPVfxZUhAMxzJ+cnkhBDPR2TGgbQvDEaNHOAT3RrrZCofKVB2/mMBhMhppfntFPcaDsk40gDTt22jM="
  bootstrapPeers:
    - "/ip4/62.169.27.162/tcp/53798/p2p/QmPYFpu244gufyvRmTbKiHhFD46QM5MuYPoFekfipKN3b6"
  protocolTimeout: "60s"

storage:
  replicationFactor: 3
  shardingEnabled: true
  proofTTL: "720h"

replication:
  strategy: "simple"
  minReplicas: 2
  healthCheckInterval: "30s"

verification:
  batchSize: 100
  timeout: "30s"
  maxVerifiers: 5

api:
  listenAddr: "0.0.0.0:5555" # Important: Bind to all interfaces
