network:
  listenAddr: "/ip4/0.0.0.0/tcp/53798"
  privateKey: "CAMSeTB3AgEBBCBTUISUaHBmdWJoih/VYXyt60jzjYBWhYWzjn+Ed60+LKAKBggqhkjOPQMBB6FEA0IABP1HQJFyVtPVfxZUhAMxzJ+cnkhBDPR2TGgbQvDEaNHOAT3RrrZCofKVB2/mMBhMhppfntFPcaDsk40gDTt22jM="
  bootstrapPeers: []  # Changed from bootstrap_peers
  protocolTimeout: "30s"  # Changed from protocol_timeout

storage:
  replicationFactor: 3  # Changed from replication_factor
  shardingEnabled: true  # Changed from sharding_enabled
  proofTTL: "720h"  # Changed from proof_ttl

replication:
  strategy: "simple"
  minReplicas: 1  # Changed from min_replicas
  healthCheckInterval: "60s"  # Changed from health_check_interval

verification:
  batchSize: 100  # Changed from batch_size
  timeout: "10s"
  maxVerifiers: 10  # Changed from max_verifiers

api:
  listenAddr: ":5555"